# Semblage v0.4.0-alpha
import cadquery as cq
# start_params
switch_diameter=40.0 # {"data_type":"number","comment":"Overall diameter of the switch, used to size other components."}
body_height=15.0 # {"data_type":"number","comment":"The height of this switch body."}
spring_diameter=25.0 # {"data_type":"number","comment":"Diameter of the spring that has been purchased."}
point_list=[(switch_diameter/2.0-2.5,0.0,0.0),(-switch_diameter/2.0+2.5,0.0,0.0),(0.0,switch_diameter/2.0-2.5,0.0),(0.0,-switch_diameter/2.0+2.5,0.0),] # {"data_type":"tuple","comment":""}
switch_holes=[(-3.25,-1.5,0.0),(3.25,-1.5,0.0),] # {"data_type":"tuple","comment":""}
leg_leads=[(0.0,0.0,0.0),(0.0,-4.08,0.0),(0.0,4.08,0.0),] # {"data_type":"tuple","comment":""}
leg_angles=[(0,-1.4,0.0),(-4.08,-1.4,0.0),(4.08,-1.4,0.0),] # {"data_type":"tuple","comment":""}
lever_height=5.0 # {"data_type":"number","comment":"1.8 is operating position, 5.0 is free position"}
button_base_pnts=[(7.0,0.0,0.0),(-7.0,0.0,0.0),] # {"data_type":"tuple","comment":""}
# end_params
switch_body=cq  # {"visible":false}
switch_body=switch_body.Workplane("XY").workplane(offset=0.0,invert=False,centerOption="CenterOfBoundBox").tag("switch_body")
switch_body=switch_body.circle(switch_diameter / 2.0,forConstruction=False)
switch_body=switch_body.extrude(body_height,combine=True,clean=True,both=False,taper=0.0)
switch_body=switch_body.faces("<Z").workplane(invert=False,centerOption="CenterOfBoundBox")
switch_body=switch_body.circle(switch_diameter / 2.0 - 2.0,forConstruction=False)
switch_body=switch_body.workplane(invert=True).cutBlind(body_height - 2.0,clean=True,taper=0.0)
switch_body=switch_body.faces(">Z[1]").workplane(invert=False,centerOption="CenterOfBoundBox")
switch_body=switch_body.circle(spring_diameter / 2.0 + 1.5,forConstruction=False)
switch_body=switch_body.cutThruAll(clean=True,taper=8)
switch_body=switch_body.faces(">Z").workplane(invert=True,centerOption="CenterOfBoundBox")
switch_body=switch_body.pushPoints(point_list)
switch_body=switch_body.circle(2.0,forConstruction=False)
switch_body=switch_body.extrude(body_height,combine=True,clean=True,both=False,taper=0.0)
switch_body=switch_body.faces("<Z").workplane(invert=True,centerOption="CenterOfBoundBox")
switch_body=switch_body.pushPoints(point_list)
switch_body=switch_body.circle(1.25,forConstruction=False)
switch_body=switch_body.cutBlind(10.0,clean=True,taper=0.0)
switch_button=cq  # {"visible":false}
switch_button=switch_button.Workplane("XY").workplane(offset=0.0,invert=False,centerOption="CenterOfBoundBox").tag("switch_button")
switch_button=switch_button.circle(spring_diameter / 2.0  + 1.5,forConstruction=False)
switch_button=switch_button.extrude(5.0,combine=True,clean=True,both=False,taper=20)
switch_button=switch_button.faces(">Z").workplane(invert=False,centerOption="CenterOfBoundBox")
switch_button=switch_button.pushPoints(button_base_pnts)
switch_button=switch_button.circle(3.4 / 2.0,forConstruction=False)
switch_button=switch_button.cutThruAll(clean=True,taper=0.0)
switch_button=switch_button.faces("<Z").workplane(invert=True,centerOption="CenterOfBoundBox")
switch_button=switch_button.circle(spring_diameter / 2.0,forConstruction=False)
switch_button=switch_button.cutBlind(3.5,clean=True,taper=0.0)
switch_button=switch_button.translate(vec=(0,0,13))
switch_bottom=cq  # {"visible":true}
switch_bottom=switch_bottom.Workplane("XY").workplane(offset=0.0,invert=False,centerOption="CenterOfBoundBox").tag("switch_bottom")
switch_bottom=switch_bottom.circle(switch_diameter / 2.0,forConstruction=False)
switch_bottom=switch_bottom.extrude(4,combine=True,clean=True,both=False,taper=0.0)
switch_bottom=switch_bottom.faces(">Z").workplane(invert=False,centerOption="CenterOfBoundBox")
switch_bottom=switch_bottom.circle(switch_diameter / 2.0 - 2.3,forConstruction=False)
switch_bottom=switch_bottom.extrude(1.0,combine=True,clean=True,both=False,taper=0.0)
switch_bottom=switch_bottom.faces(">Z[1]").workplane(invert=False,centerOption="CenterOfBoundBox")
switch_bottom=switch_bottom.polarArray(switch_diameter / 2.0 - 4.0,startAngle=45.0,angle=360.0,count=4,fill=True,rotate=True)
switch_bottom=switch_bottom.circle(2.25,forConstruction=False)
switch_bottom=switch_bottom.cutBlind(3.0,clean=True,taper=0.0)
switch_bottom=switch_bottom.faces("<Z").workplane(invert=False,centerOption="CenterOfBoundBox")
switch_bottom=switch_bottom.polarArray(switch_diameter / 2.0 - 4.0,startAngle=45,angle=360.0,count=4,fill=True,rotate=True)
switch_bottom=switch_bottom.cboreHole(3.7,6.5,3,depth=None,clean=True)
switch_bottom=switch_bottom.translate(vec=(0,0,-4.0))
switch_bottom=switch_bottom.faces(">Z").workplane(invert=False,centerOption="CenterOfBoundBox")
switch_bottom=switch_bottom.center(3.5,0.0)
switch_bottom=switch_bottom.rect(6.0,13.0,centered=True,forConstruction=False)
switch_bottom=switch_bottom.extrude(4.0,combine=True,clean=True,both=False,taper=0.0)
switch_bottom=switch_bottom.faces(">Z").workplane(invert=False,centerOption="CenterOfBoundBox")
switch_bottom=switch_bottom.center(1.25,0.0)
switch_bottom=switch_bottom.rect(3.5,13.0,centered=True,forConstruction=False)
switch_bottom=switch_bottom.extrude(6.0,combine=True,clean=True,both=False,taper=0.0)
switch_bottom=switch_bottom.faces("<X[1]").workplane(invert=False,centerOption="CenterOfBoundBox")
switch_bottom=switch_bottom.moveTo(6.0,-5.5)
switch_bottom=switch_bottom.rect(1.0,5.0,centered=True,forConstruction=False)
switch_bottom=switch_bottom.moveTo(-6.0,-5.5)
switch_bottom=switch_bottom.rect(1.0,5.0,centered=True,forConstruction=False)
switch_bottom=switch_bottom.extrude(6.0,combine=True,clean=True,both=False,taper=0.0)
switch_bottom=switch_bottom.faces(">X[-1]").workplane(invert=False,centerOption="CenterOfBoundBox")
switch_bottom=switch_bottom.center(0.0,2.5)
switch_bottom=switch_bottom.pushPoints(switch_holes)
switch_bottom=switch_bottom.circle(1.0,forConstruction=False)
switch_bottom=switch_bottom.cutThruAll(clean=True,taper=0.0)
switch_bottom=switch_bottom.faces("<Z").workplane(invert=True,centerOption="CenterOfBoundBox")
switch_bottom=switch_bottom.rarray(10.0,10.0,3,3,center=True)
switch_bottom=switch_bottom.circle(1.2,forConstruction=False)
switch_bottom=switch_bottom.cutBlind(4.0,clean=True,taper=0.0)
elec_switch=cq  # {"visible":false}
elec_switch=elec_switch.Workplane("XY").workplane(offset=0.0,invert=False,centerOption="CenterOfBoundBox").tag("elec_switch")
elec_switch=elec_switch.translate(vec=(0,0,7))
elec_switch=elec_switch.rect(5.8,12.8,centered=True,forConstruction=False)
elec_switch=elec_switch.extrude(6.5,combine=True,clean=True,both=False,taper=0.0)
elec_switch=elec_switch.faces(">X").workplane(invert=False,centerOption="CenterOfBoundBox")
elec_switch=elec_switch.pushPoints(switch_holes)
elec_switch=elec_switch.circle(1.1,forConstruction=False)
elec_switch=elec_switch.cutThruAll(clean=True,taper=0.0)
elec_switch=elec_switch.faces("<Z").workplane(invert=False,centerOption="CenterOfBoundBox")
elec_switch=elec_switch.pushPoints(leg_leads)
elec_switch=elec_switch.rect(0.4,1.0,centered=True,forConstruction=False)
elec_switch=elec_switch.extrude(2.8,combine=True,clean=True,both=False,taper=0.0)
elec_switch=elec_switch.faces(">X[1]").workplane(invert=False,centerOption="CenterOfBoundBox")
elec_switch=elec_switch.pushPoints(leg_angles)
elec_switch=elec_switch.rect(1.0,0.4,centered=True,forConstruction=False)
elec_switch=elec_switch.extrude(6.16,combine=True,clean=True,both=False,taper=0.0)
elec_switch=elec_switch.faces(">Z").workplane(invert=False,centerOption="CenterOfBoundBox")
elec_switch=elec_switch.center(0.0,1.0)
elec_switch=elec_switch.rect(3.0,12.8,centered=True,forConstruction=False)
elec_switch=elec_switch.extrude(lever_height,combine=True,clean=True,both=False,taper=0.0)
elec_switch=elec_switch.translate(vec=(0,0,5.2))
show_object(switch_bottom)
